story and rules have been added with their titles and style
WildCodeSchool/2023-09-JS-Lille-yellow-project-2-groupe1 pull request #10
Opened 2023-10-26 15:07 UTC by pagouillart

2023-10-26 15:12 UTC, Cyrildab approved these changes
Nice !

2023-10-27 07:54 UTC, Yoann-Fortin commented on frontend/src/components/HomePage/ContainerStoryRules/Rules/Rules.jsx
An h2 tag cannot be nested within a p tag

2023-10-27 07:54 UTC, Yoann-Fortin commented on frontend/src/components/HomePage/ContainerStoryRules/Rules/Rules.jsx
so the br tag is unnecessary

2023-10-27 07:56 UTC, Yoann-Fortin requested changes

2023-10-27 07:56 UTC, Yoann-Fortin commented on frontend/src/components/HomePage/ContainerStoryRules/Story/Story.jsx
Same with other comment

2023-10-27 08:31 UTC, pagouillart commented on frontend/src/components/HomePage/ContainerStoryRules/Rules/Rules.jsx
done

2023-10-27 08:31 UTC, pagouillart commented on frontend/src/components/HomePage/ContainerStoryRules/Rules/Rules.jsx
done :)

2023-10-27 08:31 UTC, pagouillart commented on frontend/src/components/HomePage/ContainerStoryRules/Story/Story.jsx
done

2023-10-27 09:30 UTC, Yoann-Fortin approved these changes

2023-10-27 09:36 UTC, merged