create inventory pop-up
WildCodeSchool/2023-09-JS-Lille-yellow-project-2-groupe1 pull request #11
Opened 2023-10-26 15:13 UTC by ItsMatDev

2023-10-26 15:17 UTC, Cyrildab approved these changes
RAS

2023-10-27 07:52 UTC, Yoann-Fortin requested changes

2023-10-27 07:52 UTC, Yoann-Fortin commented on frontend/src/components/LevelPage/GameMenu/Inventory/Inventory.scss
Responsive first always

2023-10-27 08:30 UTC, ItsMatDev commented on frontend/src/components/LevelPage/GameMenu/Inventory/Inventory.scss
responsive done

2023-10-27 09:28 UTC, Yoann-Fortin approved these changes

2023-10-27 09:35 UTC, merged