Merge feature S02 S03
WildCodeSchool/2023-09-JS-Lille-yellow-project-2-groupe1 pull request #30
Opened 2023-11-08 15:20 UTC by Bravax

2023-11-08 15:27 UTC, Yoann-Fortin commented on frontend/src/components/AboutUs/AboutUsPage.jsx
> +        <button type="button" className="closeButtonAboutUs">
The button is not necessary, instead, an aria-label is required.

2023-11-08 15:51 UTC, Yoann-Fortin requested changes

2023-11-08 15:51 UTC, Yoann-Fortin commented on frontend/src/components/AboutUs/AboutUsPage.scss
> +  margin-top: 2vw;
Not necessary with absolute position

2023-11-08 15:51 UTC, Yoann-Fortin commented on frontend/src/components/AboutUs/AboutUsPage.scss
> +  height: 3.5vw;
Not vw to a height

2023-11-08 15:51 UTC, Yoann-Fortin commented on frontend/src/components/AboutUs/AboutUsPage.scss
> +  margin-left: 2vw;
Not necessary with absolute position

2023-11-08 15:51 UTC, Yoann-Fortin commented on frontend/src/components/ChooseLevelPage/ChooseLevelPage.scss
> +  margin-top: 20px;
Not with absolute position

2023-11-08 15:51 UTC, Yoann-Fortin commented on frontend/src/components/ChooseLevelPage/ChooseLevelPage.scss
> +  margin-right: 2rem;
Not with absolute position

2023-11-08 15:51 UTC, Yoann-Fortin commented on frontend/src/components/HomePage/ContainerStoryRules/ContainerStoryRules.jsx
> +        <button type="button" className="storyRules__playButton">
Button isn't necessary

2023-11-08 15:51 UTC, Yoann-Fortin commented on frontend/src/components/HomePage/ContainerStoryRules/Rules/Rules.scss
To delete

2023-11-08 15:51 UTC, Yoann-Fortin commented on frontend/src/components/HomePage/ContainerStoryRules/Story/Story.scss
To delete

2023-11-08 15:51 UTC, Yoann-Fortin commented on frontend/src/components/HomePage/MainHeader/MainHeader.jsx
> +        <button type="button" className="aboutButton">
Button isn't necessary

2023-11-08 15:51 UTC, Yoann-Fortin commented on frontend/src/components/LevelPage/GameMenu/GameMenu.scss
> +  border-right: solid 5px #2b160f;
A color variable is better

2023-11-08 15:51 UTC, Yoann-Fortin commented on frontend/src/components/LevelPage/GameMenu/GameMenu.scss
> +  color: white;
a color variable is better

2023-11-08 15:51 UTC, Yoann-Fortin commented on frontend/src/components/LevelPage/GameMenu/GameMenu.scss
> +  margin-top: 0.5vw;
Not necessary with absolute position

2023-11-08 15:51 UTC, Yoann-Fortin commented on frontend/src/components/LevelPage/GameMenu/GameMenu.scss
> +@media screen and (min-width: 940px) {
to inverse with antother media query

2023-11-08 15:51 UTC, Yoann-Fortin commented on frontend/src/components/LevelPage/GameMenu/Inventory/Inventory.scss
> +  margin: 0 auto;
Why margin with an absolute position here ?

2023-11-08 15:51 UTC, Yoann-Fortin commented on frontend/src/components/LevelPage/GameMenu/Inventory/Inventory.scss
> +    border: 10px solid #8b4513;
A color variable is better

2023-11-08 15:51 UTC, Yoann-Fortin commented on frontend/src/components/LevelPage/GameMenu/Inventory/Inventory.scss
> +    background-color: #d2b48c;
a color variable is better

2023-11-08 15:51 UTC, Yoann-Fortin commented on frontend/src/components/LevelPage/GameMenu/Inventory/Inventory.scss
> +  border: 0;
Dead code

2023-11-08 15:51 UTC, Yoann-Fortin commented on frontend/src/components/LevelPage/GameMenu/Objectives/Objectives.scss
> +  margin: 0 auto;
dead code

2023-11-08 15:51 UTC, Yoann-Fortin commented on frontend/src/components/LevelPage/GameMenu/Objectives/Objectives.scss
> +  border: 0;
dead code

2023-11-08 15:51 UTC, Yoann-Fortin commented on frontend/src/components/LevelPage/LevelPage.scss
> +  margin-top: 20px;
Not necessary with an absolute position

2023-11-08 15:51 UTC, Yoann-Fortin commented on frontend/src/components/LevelPage/LevelPage.scss
> +  margin-right: 2rem;
Not necessary with absolute position

2023-11-08 15:51 UTC, Yoann-Fortin commented on frontend/src/components/LevelPage/ReturnGameMenu/ReturnGameMenu.jsx
> +            <button type="button" className="backtoMainMenu">
button isn't necessary

2023-11-08 15:51 UTC, Yoann-Fortin commented on frontend/src/components/LevelPage/ReturnGameMenu/ReturnGameMenu.jsx
> +        <div className="areYouSureButton">
a div ? why ?

2023-11-08 15:51 UTC, Yoann-Fortin commented on frontend/src/components/LevelPage/ReturnGameMenu/ReturnGameMenu.scss
> +  margin-top: 2vw;
Not necessary with an absolute position

2023-11-08 15:51 UTC, Yoann-Fortin commented on frontend/src/components/LevelPage/ReturnGameMenu/ReturnGameMenu.scss
> +  margin-right: 2vw;
Not necessary with an absolute position

2023-11-08 15:51 UTC, Yoann-Fortin commented on frontend/src/components/LevelPage/TargetButton/TargetButton.scss
> +  z-index: 0;
dead code

2023-11-08 15:51 UTC, Yoann-Fortin commented on frontend/src/components/LevelPage/TargetButton/TargetButton.scss
> +  margin-right: 20px;
responsive value is better

2023-11-08 15:51 UTC, Yoann-Fortin commented on frontend/src/variables.scss
> +$fontFamily: "Iceberg";
add a sans-serif font

2023-11-08 16:02 UTC, Cyrildab approved these changes

2023-11-09 13:59 UTC, Bravax commented
Resolved problems

2023-11-09 15:20 UTC, Yoann-Fortin approved these changes

2023-11-09 16:27 UTC, ItsMatDev approved these changes

2023-11-09 16:28 UTC, pagouillart approved these changes

2023-11-09 16:28 UTC, merged